apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "petestaks"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "petestaks"
    spec:
      containers:
        - name: "petestaks"
          image: "aksl5su10403.azurecr.io/petestaks"
          ports:
          - containerPort: 8123